(function() {
	// namespace:
	var o = this.jslgEngine = this.jslgEngine||{};

o.sampleXml = "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>" +
"<element>" +
"	<className>LocalRegion</className>" +
"	<key>r1</key>" +
"	<location>" +
"		<x>0</x>" +
"		<y>0</y>" +
"		<z>0</z>" +
"	</location>" +
"	<element>" +
"		<className>Icon</className>" +
"		<key>stage</key>" +
"		<linked>s1-g1</linked>" +
"	</element>" +
"	<element>" +
"		<className>Command</className>" +
"		<key>eve1</key>" +
"		<element>" +
"			<className>CommandBlockIF</className>" +
"			<argument>10+5==15</argument>" +
"			<element>" +
"			    <type>Element</type>" +
"			    <className>ActionLog</className>" +
"			    <argument>test</argument>" +
"			</element>" +
"		</element>" +
"	</element>" +
"	<element>" +
"		<className>StageFrame</className>" +
"		<key>rs1</key>" +
"		<element>" +
"			<className>Status</className>" +
"			<key>life</key>" +
"			<value>2</value>" +
"		</element>" +
"	</element>" +
"	<element>" +
"		<className>GroundFrame</className>" +
"		<key>rg1</key>" +
"		<element>" +
"			<className>Status</className>" +
"			<key>life</key>" +
"			<value>2</value>" +
"		</element>" +
"	</element>" +
"	<element>" +
"		<className>CastFrame</className>" +
"		<key>rc1</key>" +
"	</element>" +
"	<element>" +
"		<className>ItemFrame</className>" +
"		<key>ri1</key>" +
"		<element>" +
"			<className>Command</className>" +
"			<key>e1</key>" +
"			<element>" +
"				<className>ActionLog</className>" +
"				<argument>test</argument>" +
"       	</element>" +
"		</element>" +
"	</element>" +
"	<element>" +
"			<className>Stage</className>" +
"			<source>rs1</source>" +
"			<location>" +
"				<x>0</x>" +
"				<y>0</y>" +
"				<z>0</z>" +
"			</location>" +
"			<key>s1</key>" +
"			<element>" +
"				<className>Ground</className>" +
"				<source>rg1</source>" +
"				<location>" +
"					<x>0</x>" +
"					<y>0</y>" +
"					<z>0</z>" +
"				</location>" +
"				<key>g1</key>" +
"				<element>" +
"					<className>Cast</className>" +
"					<source>rc1</source>" +
"					<key>c1</key>" +
"					<element>" +
"						<className>Item</className>" +
"						<source>ri1</source>" +
"						<key>i1</key>" +
"					</element>" +
"					<element>" +
"						<className>Status</className>" +
"						<key>life</key>" +
"						<value>2</value>" +
"					</element>" +
"				</element>" +
"			</element>" +
"	</element>" +
"</element>";
})();
